language: scala
scala:
- 2.11.7
- 2.10.6
jdk:
- oraclejdk7
script: sbt ++${TRAVIS_SCALA_VERSION} test $(if [[ "${TRAVIS_PULL_REQUEST}" == "false"
  && ${JAVA_HOME} == $(jdk_switcher home oraclejdk7) && "${TRAVIS_BRANCH}" == "temporary-shapeless"
  ]]; then echo "publish"; fi)
sudo: false
env:
  global:
  - secure: Ncsr7s5sg1lc1sZh1SErxvn4dtqKg42M7xtiPbmbmbst4atV/rznD4PMGL7g72t4x5Zhagn4751Ojk3fSOWQpbgLwb1W9lKSG7sHOTmexHAbWcNjxKYGt9OIeoCs6q+B6z/7VbZKqzNxstclJFSgYJteGNAc3kqf0UdqgH06BFGxqV3Zk2Z6ln6E2VD3l8okfyV7Kb3G+Ub54wa3m6yDKWr5z0lmuWCEiVClnetMlbZjSyNKwsJkZ5n7MZDSQdi68Uy/Nj2rLP1LIR0rs+/limGjNmMBmhJ971+QSTswr371L8C9/N0NGmUjqBk1iUtCMq/Dgj0e86h0ucSmnJUPyB5L4+J7v3DUiXeF3j5Au8pTLgRJ4rIec4yNl0oiqAv2NQFgFGNf0W8qFYC0VB3KHQ15v52YPytAgpfOQ2DOpMFkbPq1s/3zfMYFSRIiL1nXredJ/HICChUhoioGsGXkkPClngcTHRj8A9KopqG1I13P2Aq5xZGVf4FeSrU+0hpvrabKJqLak/0AYLyorNEwxzsR5zYzDmFk/vI83O2+WfA2g2xTGLkJYn75KtHMo71wfRhph65Fj+3NXKjLb0q/egEw/wV8+U2hasjO8PxOpqHL8UUiIXS69waujtTT2lPAb3693GGYrqWhak+9vhTA9Ez3w3v5/kctAn7OlBdaAyM=
  - secure: oFDs03AIcOORKxvayDC1UVH/LqaKq4c7mdm2+v8fi4vdcojEtAw5VRfS8fzNmkZeYsY6rxC+TMEQ3UkJ5lmSzuUrvpJyt05DgYu7nOTUZ0lEmOGIDaI3hmg/e/f12hjY2Bvml+pkE8YCGx8FgV9T2QKIYus1fqFyo+s+XB1HzlhHTYrVf+5SbHK8UJyEQdhpT5ysR0KbPVZmDp/cLFqGlcgRwo5H0HW1kgKPio7XVzAsH1dFwj7zxzPEuX5m9JRmwMcLYn/Ae6yygtD8/uwEU7iUQBVBptm1PecqTk9qRTMjihcA+S0imZffPQGPlqWuE+/Gbf/9rc84H+6ItLW5Pve++AX4ns07y+sbDjlM9Yro43yPWxQKDwS50E7Zpn2TdjuL+E2s5cL7Bw4pTeOUX4m54p7bH5xrrWnvlelXD7/SufrpGZUtUS8z2WbUYJCD9a04875cXt62R1QKHVpEAgyzyRpdjOBf+W21CrXvuVfE+ZEFYbt3Ml3G/rIbgPg0dq/o/kYuFxQdZCNDOBGmAe7w0x3FOuR0h4158/1H+icIyg2MgbFWDpjJ80Tg50TDxLRtQBpgWosCG7P+KvGALk/mBUGg+aGZ+piTT7NSkfR7vzls3atOpsXmwPp0vdiTiCn/PAibmlhe/pCg9Eku4DtdlyggIeqGOYCPT4AYxM8=
